/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import java.awt.*;
import java.awt.event.ComponentAdapter;
import java.awt.event.ComponentEvent;
import javax.swing.*;
import javax.swing.border.Border;

/**
 *
 * @author cucchiarini.cesare
 */
public class Form extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Form.class.getName());
    
    private GestoreGioco g;
    private JPanel[] panels = new JPanel[9];
    private JPanel campo;
    private JLabel tempo;
    private JLabel punteggio;
    private JPanel infos;
    
    public Form() {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        this.setLayout(new BorderLayout());       
        
        preparaCampo();
        preparaPunteggio();        
        
        this.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowOpened(java.awt.event.WindowEvent e) {
                infos.setPreferredSize(new Dimension(e.getWindow().getWidth()/5, 0));
                infos.revalidate();
                infos.repaint();
                
                g = new GestoreGioco(new Talpa(3, campo.getSize().width/3, campo.getSize().height/3), new Giocatore(), panels, punteggio);  
                g.start();
            }
        });
    }
    
    public void preparaCampo(){
        campo = new JPanel();
        campo.setBackground(Color.GREEN);
        campo.setLayout(new GridLayout(3, 3, 30, 0));      
        
        for (int i = 0; i < 9; i++) {
            JPanel p = new JPanel(){
                @Override
                protected void paintComponent(Graphics g) {
                    Graphics2D g2d = (Graphics2D) g.create();
                    g2d.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);

                    g2d.setColor(Color.black);
                    g2d.fillOval(0, 0, getWidth() - 1, getHeight() - 1);

                    g2d.dispose();
                }
            };
            p.setLayout(new BorderLayout());
            p.setOpaque(false);
            panels[i] = p;
            campo.add(p);
        }
        
        this.add(campo, BorderLayout.CENTER);
    }
    public void preparaPunteggio(){
        infos = new JPanel();
        infos.setLayout(new BoxLayout(infos, BoxLayout.Y_AXIS));
        
        tempo = new JLabel("30");
        tempo.setAlignmentX(CENTER_ALIGNMENT);
        punteggio = new JLabel("0");
        punteggio.setAlignmentX(CENTER_ALIGNMENT);
        
        Font f = new Font(tempo.getFont().getFontName(), Font.PLAIN, 40);
        tempo.setFont(f);
        punteggio.setFont(f);
        
        Border b = BorderFactory.createCompoundBorder(BorderFactory.createLineBorder(Color.LIGHT_GRAY, 3), 
                BorderFactory.createLineBorder(Color.BLACK));
        b = BorderFactory.createCompoundBorder(BorderFactory.createLineBorder(Color.BLACK), b);
        tempo.setBorder(b);
        punteggio.setBorder(b);
        
        infos.add(Box.createVerticalGlue());     
        infos.add(tempo);
        infos.add(Box.createRigidArea(new Dimension(0, 30)));       
        infos.add(punteggio);
        infos.add(Box.createVerticalGlue());
        
        infos.setBackground(Color.WHITE);
        this.add(infos, BorderLayout.EAST);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Form().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
