/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.ComponentAdapter;
import java.awt.event.ComponentEvent;
import javax.swing.*;
import javax.swing.border.Border;

/**
 *
 * @author cucchiarini.cesare
 */
public class Form extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Form.class.getName());
    
    private GestoreGioco g;
    private JPanel[] panels = new JPanel[9];
    private JPanel campo;
    private JLabel tempo = new JLabel("30");
    private JLabel punteggio = new JLabel("0");
    private JPanel infos;
    private IntBox box = new IntBox();
    private int punti = 0;
    private Timer timer;
    private Thread threadPunteggio;
    private JButton bottoneAvvio = new JButton("Avvia Gioco");
    private JPanel intro;
    
    public Form() {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        this.setLayout(new BorderLayout());
        this.add(campo, BorderLayout.CENTER);
        this.add(infos, BorderLayout.EAST);
        this.add(intro, BorderLayout.CENTER);
        
        bottoneAvvio.addActionListener(new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent e){
                campo = GeneratoreInterfaccia.preparaCampo(panels);
                infos = GeneratoreInterfaccia.preparaPunteggio(tempo, punteggio);
                
                campo.revalidate();
                campo.repaint();
                infos.revalidate();
                infos.repaint();
                preparaLogica();
            }
        });
    }
    
    
    public void preparaLogica(){
        this.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowOpened(java.awt.event.WindowEvent e) {
                new Thread(()-> {
                    infos.setPreferredSize(new Dimension(e.getWindow().getWidth()/5, 0));
                    infos.revalidate();
                    infos.repaint();

                    g = new GestoreGioco(new Talpa(3, campo.getSize().width/3, campo.getSize().height/3), new Giocatore(), panels, box);      
                    threadPunteggio = new Thread(()->{
                        boolean flag = true;
                        synchronized(box){
                            while(flag){
                                try {
                                    box.wait();
                                } catch (InterruptedException ex) {flag = false;}
                                punti += box.getPunti();
                                punteggio.setText(""+punti);
                            }
                        }
                    });
                    timer = new Timer(1000, ex->{
                        tempo.setText((Integer.parseInt(tempo.getText())-1) +"");
                        if(tempo.getText().equals("0")){
                            g.interrupt();
                            timer.stop();
                            threadPunteggio.interrupt();
                        }
                    });

                    try {
                        Thread.sleep(1500);
                    } catch (InterruptedException ex) {}
                    threadPunteggio.start();
                    g.start();
                    timer.start();
                }).start();           
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Form().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
